import Link from 'next/link'
import { StorefrontFrame } from '@/components/storefront-header'

const catalog: Record<string, { title: string; description: string; products: [string, string, string][] }> = {
  't-shirts': { title: 'T-shirts', description: 'Graphic tees, everyday essentials, and relaxed fits.', products: [['One Life Graphic T-shirt', '/products/one-life-front.png', '$260'], ['Gradient Graphic T-shirt', '/products/one-life-back.png', '$145'], ['Black Striped T-shirt', '/products/one-life-model.png', '$120']] },
  shirts: { title: 'Shirts', description: 'Polished shirts for workdays, weekends, and everywhere between.', products: [['Checkered Shirt', '/products/one-life-front.png', '$180'], ['Vertical Striped Shirt', '/products/one-life-back.png', '$212'], ['Relaxed Oxford Shirt', '/products/one-life-model.png', '$190']] },
  jeans: { title: 'Jeans', description: 'Reliable denim in modern cuts and comfortable washes.', products: [['Skinny Fit Jeans', '/products/one-life-front.png', '$240'], ['Straight Leg Jeans', '/products/one-life-back.png', '$220'], ['Washed Blue Jeans', '/products/one-life-model.png', '$195']] },
  hoodies: { title: 'Hoodies', description: 'Soft layers made for cooler days and slower mornings.', products: [['Essential Hoodie', '/products/one-life-front.png', '$160'], ['Graphic Pullover', '/products/one-life-back.png', '$175'], ['Heavyweight Hoodie', '/products/one-life-model.png', '$210']] },
  shorts: { title: 'Shorts', description: 'Easy summer styles with room to move.', products: [['Bermuda Shorts', '/products/one-life-front.png', '$80'], ['Relaxed Chino Shorts', '/products/one-life-back.png', '$95'], ['Active Shorts', '/products/one-life-model.png', '$75']] },
  'dress-style': { title: 'Dress Style', description: 'Curated looks for casual, formal, party, and gym days.', products: [['Casual Essential', '/products/one-life-front.png', '$145'], ['Formal Edit', '/products/one-life-back.png', '$220'], ['Party Statement', '/products/one-life-model.png', '$180']] },
  sale: { title: 'On Sale', description: 'Limited-time prices on customer favorites.', products: [['Sale Graphic T-shirt', '/products/one-life-front.png', '$99'], ['Sale Polo', '/products/one-life-back.png', '$120'], ['Sale Striped Tee', '/products/one-life-model.png', '$85']] },
  'new-arrivals': { title: 'New Arrivals', description: 'Fresh silhouettes and new colorways just added.', products: [['New Graphic T-shirt', '/products/one-life-front.png', '$145'], ['New Overshirt', '/products/one-life-back.png', '$190'], ['New Relaxed Tee', '/products/one-life-model.png', '$130']] },
  brands: { title: 'Brands', description: 'Explore styles from the brands our community loves.', products: [['Signature Tee', '/products/one-life-front.png', '$145'], ['Modern Polo', '/products/one-life-back.png', '$180'], ['Classic Shirt', '/products/one-life-model.png', '$200']] },
}

export default async function CategorySlugPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const category = catalog[slug] ?? catalog['t-shirts']
  return <StorefrontFrame><div className="min-h-screen bg-white px-4 py-8 text-[#111] sm:px-12"><div className="mx-auto max-w-[1180px]"><Link href="/" className="text-xl font-black tracking-[-1px]">SHOP.CO</Link><nav className="mt-8 text-xs text-[#777]"><Link href="/">Home</Link><span className="mx-2">›</span>{category.title}</nav><div className="mt-8 flex items-end justify-between gap-4"><div><h1 className="text-4xl font-black tracking-tight">{category.title}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#666]">{category.description}</p></div><span className="text-xs text-[#777]">{category.products.length} Products</span></div><section className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-3">{category.products.map(([name, image, price]) => <Link href="/product" key={name} className="group"><div className="aspect-square overflow-hidden rounded-xl bg-[#f0f0f0]"><img src={image} alt={name} className="h-full w-full object-contain transition-transform duration-300 group-hover:scale-105" /></div><h2 className="mt-3 text-sm font-bold">{name}</h2><div className="mt-2 text-amber-500">★★★★★ <span className="text-xs text-[#777]">4.5/5</span></div><p className="mt-1 font-bold">{price}</p></Link>)}</section></div></div></StorefrontFrame>
}
