'use client'

import { ArrowRight, CheckCircle2, ChevronLeft, ChevronRight, ShoppingCart, Star } from 'lucide-react'
import { StorefrontFrame } from '@/components/storefront-header'
import { toast } from 'sonner'

const catalogImage = '/products/home-catalog.png'
const heroImage = '/products/home-hero.png'
const styleImage = '/products/home-style.png'
const brandLogos = [
  ['versace', 'Versace'],
  ['zara', 'Zara'],
  ['gucci', 'Gucci'],
  ['prada', 'Prada'],
  ['calvinklein', 'Calvin Klein'],
]
const products = [
  ['T-shirt with Tape Details', '$120', '50% 50%', '/products/arrival-tape-shirt.png'], ['Skinny Fit Jeans', '$240', '50% 50%', '/products/arrival-jeans.png'], ['Checkered Shirt', '$180', '50% 50%', '/products/arrival-shirt.png'], ['Sleeve Striped T-shirt', '$130', '50% 50%', '/products/arrival-striped.png'],
]
const topSelling = [['Vertical Striped Shirt', '$212', '50% 50%', '/products/top-striped-shirt.png'], ['Courage Graphic T-shirt', '$145', '50% 50%', '/products/top-graphic-shirt.png'], ['Loose Fit Bermuda Shorts', '$80', '50% 50%', '/products/top-shorts.png'], ['Faded Skinny Jeans', '$210', '50% 50%', '/products/top-faded-jeans.png']]

const customerReviews = [['Sarah M.', 'I’m blown away by the quality and style of the clothes I received from Shop.co. From casual wear to elegant dresses, every piece I’ve bought has exceeded my expectations.'], ['Alex K.', 'Finding clothes that align with my personal style used to be a challenge until I discovered Shop.co. The range of options they offer is truly remarkable, catering to a variety of tastes.'], ['James L.', 'As someone who’s always on the lookout for unique fashion pieces, I’m thrilled to have stumbled upon Shop.co. The selection of clothes is not only diverse but on-point with trends.']]

function ReviewCarousel() {
  return <section className="overflow-hidden py-12"><div className="flex items-center justify-between gap-6"><h2 className="text-3xl font-black tracking-[-1.5px] sm:text-5xl">OUR HAPPY CUSTOMERS</h2><div className="flex shrink-0 items-center gap-5"><button type="button" aria-label="Previous customer review" className="transition hover:scale-110"><ChevronLeft size={24} strokeWidth={2} /></button><button type="button" aria-label="Next customer review" className="transition hover:scale-110"><ChevronRight size={24} strokeWidth={2} /></button></div></div><div className="mt-10 grid gap-6 md:grid-cols-3">{customerReviews.map(([name, quote]) => <blockquote key={name} className="min-h-[265px] rounded-3xl border border-[#dedede] bg-white p-7"><div className="flex gap-1 text-[#f5bd2e]" aria-label="5 out of 5 stars">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={20} fill="currentColor" strokeWidth={0} />)}</div><div className="mt-6 flex items-center gap-2"><b className="text-lg">{name}</b><CheckCircle2 className="size-6 fill-[#3fbd68] text-white" aria-label="Verified customer" /></div><p className="mt-4 text-base leading-6 text-[#666]">{quote}</p></blockquote>)}</div></section>
}

function ProductCard({ item }: { item: string[] }) { const addToCart = () => { const match = document.cookie.match(/(?:^|; )shop_cart=([^;]*)/); const cart = match ? JSON.parse(decodeURIComponent(match[1])) : []; const next = [...cart, { id: Date.now(), name: item[0], price: Number(item[1].replace('$', '')), image: item[3] || catalogImage, quantity: 1 }]; document.cookie = `shop_cart=${encodeURIComponent(JSON.stringify(next))}; path=/; max-age=2592000`; window.dispatchEvent(new Event('cart-updated')); toast.success(`${item[0]} added to your cart`, { description: 'You can review your items from the cart.', action: { label: 'View cart', onClick: () => { window.location.href = '/cart' } } }); }; return <article className="min-w-0"><a href="/product" className="block"><div className="aspect-square overflow-hidden rounded-lg bg-[#f1f1f1]"><img src={item[3] || catalogImage} alt={item[0]} className="h-full w-full object-contain p-3" style={{ objectPosition: item[2] }} /></div><h3 className="mt-2 truncate text-sm font-bold sm:text-base">{item[0]}</h3></a><div className="mt-2 flex items-center gap-1 text-xs text-amber-500 sm:text-sm"><Star size={14} fill="currentColor" /> <span className="text-[#777]">4.5/5</span></div><p className="mt-1 text-sm font-bold sm:text-base">{item[1]}</p><button type="button" onClick={addToCart} className="mt-3 flex w-full items-center justify-center gap-2 rounded-full bg-black py-2.5 text-xs font-semibold text-white sm:text-sm"><ShoppingCart size={15} /> Add to Cart</button></article> }

export default function HomePage() { return <StorefrontFrame>
  <section className="relative left-1/2 w-screen -translate-x-1/2 overflow-hidden bg-[#f2f0ed] px-4 py-8 sm:px-12 md:min-h-0 md:max-h-[750px] md:py-20"><div className="relative z-10 flex max-w-[430px] flex-col items-start justify-center md:min-h-[710px] md:w-1/2"><p className="mb-3 text-xs font-semibold uppercase tracking-[2px] sm:text-sm">New season / 2024</p><h1 className="text-balance text-[36px] font-black leading-[.95] tracking-[-1.5px] sm:text-[58px]">FIND CLOTHES THAT MATCHES YOUR STYLE</h1><p className="mt-4 max-w-[370px] text-sm leading-6 text-[#666] sm:text-base">Browse through our diverse range of meticulously crafted garments, designed to bring out your individuality.</p><a href="/shop" className="mt-6 inline-flex items-center rounded-full bg-black px-8 py-3 text-sm font-semibold text-white">Shop Now <ArrowRight className="ml-2" size={14} /></a><div className="mt-6 grid grid-cols-2 gap-x-4 gap-y-3 text-center text-xs leading-5 text-[#555] sm:flex sm:gap-5 sm:text-left sm:text-sm"><span><b className="block text-lg text-black">200+</b>International Brands</span><span><b className="block text-lg text-black">2,000+</b>High-Quality Products</span><span className="col-span-2 sm:col-span-1"><b className="block text-lg text-black">30,000+</b>Happy Customers</span></div></div><img loading="eager" src={heroImage} alt="SHOP.CO style collection" className="relative mt-6 block h-[400px] w-full object-cover object-[58%_38%] sm:absolute sm:inset-y-0 sm:right-0 sm:mt-0 sm:h-full sm:w-[50%] sm:max-w-[50%] sm:object-cover sm:object-center md:block" /></section>
  <div className="relative left-1/2 grid w-screen -translate-x-1/2 grid-cols-2 items-center justify-items-center gap-5 bg-black px-6 py-5 sm:grid-cols-5 sm:gap-3">{brandLogos.map(([slug, name]) => <div key={slug} aria-label={`${name} logo`} className="font-sans text-sm font-bold tracking-tight text-white sm:text-base">{name}</div>)}</div>
  <section className="py-10"><h2 className="text-center text-2xl font-black tracking-[-1px]">NEW ARRIVALS</h2><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{products.map(item => <ProductCard item={item} key={item[0]} />)}</div><a href="/shop" className="mx-auto mt-7 block w-fit rounded-full border border-[#ddd] px-8 py-2 text-xs">View All</a></section>
  <section className="border-t border-[#eee] py-10"><h2 className="text-center text-2xl font-black tracking-[-1px]">TOP SELLING</h2><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{topSelling.map(item => <ProductCard item={item} key={item[0]} />)}</div><a href="/shop" className="mx-auto mt-7 block w-fit rounded-full border border-[#ddd] px-8 py-2 text-xs">View All</a></section>
  <section className="rounded-2xl bg-[#f1f1f1] p-6 sm:p-10"><h2 className="text-center text-2xl font-black tracking-[-1px] sm:text-3xl">BROWSE BY CATEGORY</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['T-shirts','t-shirts','/products/category-tshirts.png'],['Shirts','shirts','/products/category-shirts.png'],['Jeans','jeans','/products/category-jeans.png'],['Hoodies','hoodies','/products/category-hoodies.png'],['Shorts','shorts','/products/category-shorts.png'],['Dress Style','dress-style','/products/category-dress-style.png']].map(([name, slug, image]) => <a key={slug} href={`/category/${slug}`} className="relative h-36 overflow-hidden rounded-lg bg-white p-5 text-base font-bold sm:h-44 sm:text-lg"><span className="relative z-10">{name}</span><img src={image} alt={`${name} category`} className="absolute inset-0 h-full w-full object-contain opacity-75 transition-transform duration-300 hover:scale-105" /></a>)}</div></section>
  <ReviewCarousel />
  </StorefrontFrame> }
