'use client'

import { CheckCircle2, ChevronLeft, ChevronRight, ShoppingCart, Star } from 'lucide-react'
import { StorefrontFrame } from '@/components/storefront-header'
import { Separator } from '@/components/ui/separator'
import { toast } from 'sonner'
import { useEffect, useState } from 'react'

const catalogImage = '/products/home-catalog.png'
const heroImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Rectangle%202-3tHplLk9mcJSEp73ASbEd4hC9ZDh88.png'
const styleImage = '/products/home-style.png'
const brandLogos = [
  ['versace', 'Versace'],
  ['zara', 'Zara'],
  ['gucci', 'Gucci'],
  ['prada', 'Prada'],
  ['calvinklein', 'Calvin Klein'],
]
const products = [
  ['T-shirt with Tape Details', '$120', '50% 50%', '/products/arrival-tape-shirt.png'], ['Skinny Fit Jeans', '$240', '50% 50%', '/products/arrival-jeans.png'], ['Checkered Shirt', '$180', '50% 50%', '/products/arrival-shirt.png'], ['Sleeve Striped T-shirt', '$130', '50% 50%', '/products/arrival-striped.png'],
]
const topSelling = [['Vertical Striped Shirt', '$212', '50% 50%', '/products/top-striped-shirt.png'], ['Courage Graphic T-shirt', '$145', '50% 50%', '/products/top-graphic-shirt.png'], ['Loose Fit Bermuda Shorts', '$80', '50% 50%', '/products/top-shorts.png'], ['Faded Skinny Jeans', '$210', '50% 50%', '/products/top-faded-jeans.png']]

const customerReviews = [['Sarah M.', 'I’m blown away by the quality and style of the clothes I received from Shop.co. From casual wear to elegant dresses, every piece I’ve bought has exceeded my expectations.'], ['Alex K.', 'Finding clothes that align with my personal style used to be a challenge until I discovered Shop.co. The range of options they offer is truly remarkable, catering to a variety of tastes.'], ['James L.', 'As someone who’s always on the lookout for unique fashion pieces, I’m thrilled to have stumbled upon Shop.co. The selection of clothes is not only diverse but on-point with trends.'], ['Olivia R.', 'The fit, fabric, and attention to detail are exceptional. Shop.co makes it easy to build a wardrobe that feels both comfortable and completely personal.'], ['Daniel T.', 'Every order has arrived quickly and looked even better in person. I appreciate the thoughtful designs and the quality that lasts after every wash.'], ['Mia W.', 'I finally found a store that understands my style. The collection is versatile, the sizing is reliable, and the whole shopping experience feels effortless.']]

function ReviewCarousel() {
  const [start, setStart] = useState(0)
  useEffect(() => { const timer = window.setInterval(() => setStart((current) => current >= customerReviews.length - 3 ? 0 : current + 1), 4500); return () => window.clearInterval(timer) }, [])
  return <section className="overflow-hidden py-12"><div className="flex items-center justify-between gap-6"><h2 className="text-3xl font-black tracking-[-1.5px] sm:text-5xl">OUR HAPPY CUSTOMERS</h2><div className="flex shrink-0 items-center gap-5"><button type="button" aria-label="Previous customer review" onClick={() => setStart((start - 1 + customerReviews.length - 2) % (customerReviews.length - 2))} className="transition hover:scale-110"><ChevronLeft size={24} strokeWidth={1.5} aria-hidden="true" /></button><button type="button" aria-label="Next customer review" onClick={() => setStart((start + 1) % (customerReviews.length - 2))} className="transition hover:scale-110"><ChevronRight size={24} strokeWidth={1.5} aria-hidden="true" /></button></div></div><div className="mt-10 overflow-hidden"><div className="grid w-[600%] grid-cols-6 gap-6 transition-transform duration-500 ease-out md:w-[200%]" style={{ transform: `translateX(-${start * 16.6667}%)` }}>{customerReviews.map(([name, quote]) => <blockquote key={name} className="min-h-[265px] rounded-3xl border border-[#dedede] bg-white p-7"><div className="flex gap-1 text-[#f5bd2e]" aria-label="5 out of 5 stars">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={20} fill="currentColor" strokeWidth={0} />)}</div><div className="mt-6 flex items-center gap-2"><b className="text-lg">{name}</b><CheckCircle2 className="size-6 fill-[#3fbd68] text-white" aria-label="Verified customer" /></div><p className="mt-4 text-base leading-6 text-[#666]">{quote}</p></blockquote>)}</div></div></section>
}

function ProductCard({ item }: { item: string[] }) { const addToCart = () => { const match = document.cookie.match(/(?:^|; )shop_cart=([^;]*)/); const cart = match ? JSON.parse(decodeURIComponent(match[1])) : []; const next = [...cart, { id: Date.now(), name: item[0], price: Number(item[1].replace('$', '')), image: item[3] || catalogImage, quantity: 1 }]; document.cookie = `shop_cart=${encodeURIComponent(JSON.stringify(next))}; path=/; max-age=2592000`; window.dispatchEvent(new Event('cart-updated')); toast.success(`${item[0]} added to your cart`, { description: 'You can review your items from the cart.', action: { label: 'View cart', onClick: () => { window.location.href = '/cart' } } }); }; return <article className="min-w-0"><a href="/product" className="block"><div className="aspect-square overflow-hidden rounded-lg bg-[#f1f1f1]"><img src={item[3] || catalogImage} alt={item[0]} className="h-full w-full object-contain p-3" style={{ objectPosition: item[2] }} /></div><h3 className="mt-3 truncate text-base font-black leading-6 sm:text-lg">{item[0]}</h3></a><div className="mt-2 flex items-center gap-1 text-xs text-amber-500 sm:text-sm"><span className="flex">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={14} fill="currentColor" strokeWidth={0} />)}</span><span className="text-[#777]">4.5/5</span></div><div className="mt-2 flex items-center gap-2"><p className="text-xl font-bold">{item[1]}</p><span className="text-base text-[#999] line-through">${Math.round(Number(item[1].replace('$', '')) * 1.25)}</span><span className="rounded-full bg-[#ffe7e7] px-3 py-1 text-xs font-medium text-[#ff5a5f]">-20%</span></div><button type="button" onClick={addToCart} className="mt-3 flex w-full items-center justify-center gap-2 rounded-full bg-black py-2.5 text-xs font-semibold text-white sm:text-sm"><ShoppingCart size={15} /> Add to Cart</button></article> }

export default function HomePage() { return <StorefrontFrame>
  <section className="relative left-1/2 w-screen -translate-x-1/2 overflow-hidden bg-[#f2f0ed] px-4 py-8 sm:px-12 md:min-h-[700px] md:py-0"><div className="relative z-10 flex w-full flex-col items-start justify-center md:min-h-[700px] md:w-1/2 md:max-w-[50%]"><h1 className="max-w-[680px] text-balance text-[40px] font-black leading-[.95] tracking-[-1.5px] sm:text-[64px]">FIND CLOTHES THAT MATCHES YOUR STYLE</h1><p className="mt-4 max-w-[370px] text-sm leading-6 text-[#666] sm:text-base">Browse through our diverse range of meticulously crafted garments, designed to bring out your individuality.</p><a href="/shop" className="mt-6 inline-flex items-center rounded-full bg-black px-8 py-3 text-xs font-medium text-white">Shop Now</a><div className="mt-8 grid w-full max-w-[700px] grid-cols-3 items-center text-left text-[10px] font-normal leading-4 text-[#666]"><span className="relative min-w-0 px-6 first:pl-0"><b className="block text-[30px] font-bold leading-9 tracking-tight text-black sm:text-[40px]">200+</b>International Brands<Separator orientation="vertical" className="absolute right-0 top-0 h-16 w-px bg-[#d8d8d8]" /></span><span className="relative min-w-0 px-6"><b className="block text-[30px] font-bold leading-9 tracking-tight text-black sm:text-[40px]">2,000+</b>High-Quality Products<Separator orientation="vertical" className="absolute right-0 top-0 h-16 w-px bg-[#d8d8d8]" /></span><span className="min-w-0 px-6 last:pr-0"><b className="block text-[30px] font-bold leading-9 tracking-tight text-black sm:text-[40px]">30,000+</b>Happy Customers</span></div></div><img loading="eager" src={heroImage} alt="SHOP.CO style collection" className="absolute inset-0 h-full w-full object-cover object-center" /><span aria-hidden="true" className="absolute right-[8%] top-[12%] z-10 size-[72px] bg-black [clip-path:polygon(50%_0,59%_38%,100%_50%,59%_62%,50%_100%,41%_62%,0_50%,41%_38%)]" /><span aria-hidden="true" className="absolute right-[46%] top-[42%] z-10 size-10 bg-black [clip-path:polygon(50%_0,59%_38%,100%_50%,59%_62%,50%_100%,41%_62%,0_50%,41%_38%)]" /></section>
  <div className="relative left-1/2 grid w-screen -translate-x-1/2 grid-cols-2 items-center justify-items-center gap-5 bg-black px-6 py-5 sm:grid-cols-5 sm:gap-3">{brandLogos.map(([slug, name]) => <div key={slug} aria-label={`${name} logo`} className="font-sans text-sm font-bold tracking-tight text-white sm:text-base">{name}</div>)}</div>
  <section className="py-10"><h2 className="text-center text-3xl font-black tracking-[-1.5px] sm:text-5xl">NEW ARRIVALS</h2><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{products.map(item => <ProductCard item={item} key={item[0]} />)}</div><a href="/shop" className="mx-auto mt-7 block w-fit rounded-full border border-[#ddd] px-8 py-2 text-xs">View All</a></section>
  <section className="border-t border-[#eee] py-10"><h2 className="text-center text-3xl font-black tracking-[-1.5px] sm:text-5xl">TOP SELLING</h2><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{topSelling.map(item => <ProductCard item={item} key={item[0]} />)}</div><a href="/shop" className="mx-auto mt-7 block w-fit rounded-full border border-[#ddd] px-8 py-2 text-xs">View All</a></section>
  <section className="rounded-[2rem] bg-[#f1f1f1] p-6 sm:p-10 lg:p-14"><h2 className="text-center text-3xl font-black tracking-[-1.5px] sm:text-5xl">BROWSE BY DRESS STYLE</h2><div className="mt-8 grid gap-4 md:grid-cols-2"><a href="/category/dress-style" className="relative h-52 overflow-hidden rounded-2xl bg-white p-6 text-3xl font-medium sm:h-64"><span className="relative z-10">Casual</span><img src="/products/category-tshirts.png" alt="Casual dress style" className="absolute inset-y-0 right-0 h-full w-3/4 object-cover object-center transition-transform duration-300 hover:scale-105" /></a><a href="/category/shirts" className="relative h-52 overflow-hidden rounded-2xl bg-white p-6 text-3xl font-medium sm:h-64"><span className="relative z-10">Formal</span><img src="/products/category-shirts.png" alt="Formal dress style" className="absolute inset-y-0 right-0 h-full w-3/4 object-cover object-center transition-transform duration-300 hover:scale-105" /></a><a href="/category/dress-style" className="relative h-52 overflow-hidden rounded-2xl bg-white p-6 text-3xl font-medium sm:h-64"><span className="relative z-10">Party</span><img src="/products/category-dress-style.png" alt="Party dress style" className="absolute inset-y-0 right-0 h-full w-3/4 object-cover object-center transition-transform duration-300 hover:scale-105" /></a><a href="/category/hoodies" className="relative h-52 overflow-hidden rounded-2xl bg-white p-6 text-3xl font-medium sm:h-64"><span className="relative z-10">Gym</span><img src="/products/category-hoodies.png" alt="Gym dress style" className="absolute inset-y-0 right-0 h-full w-3/4 object-cover object-center transition-transform duration-300 hover:scale-105" /></a></div></section>
  <ReviewCarousel />
  </StorefrontFrame> }
