'use client'

import { ArrowRight, ChevronLeft, ChevronRight, Star } from 'lucide-react'
import { StorefrontFrame } from '@/components/storefront-header'

const catalogImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-QdCrvWBNsQ1OL0tMan0yI7d01feYLQ.png'
const heroImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-BED7XcTLYSwwCuTP0m9wji6bqz3tXl.png'
const products = [
  ['T-shirt with Tape Details', '$120', '22% 29%'], ['Skinny Fit Jeans', '$240', '38% 34%'], ['Checkered Shirt', '$180', '56% 34%'], ['Sleeve Striped T-shirt', '$130', '75% 34%'],
]
const topSelling = [['Vertical Striped Shirt', '$212', '24% 74%'], ['Courage Graphic T-shirt', '$145', '42% 74%'], ['Loose Fit Bermuda Shorts', '$80', '63% 74%'], ['Faded Skinny Jeans', '$210', '82% 74%']]

function ProductCard({ item }: { item: string[] }) { return <article className="min-w-0"><div className="aspect-square overflow-hidden rounded-lg bg-[#f1f1f1]"><img src={catalogImage} alt={item[0]} className="h-full w-full scale-[2.7] object-cover" style={{ objectPosition: item[2] }} /></div><h3 className="mt-2 truncate text-[11px] font-bold">{item[0]}</h3><div className="mt-1 flex items-center gap-1 text-[9px] text-amber-500"><Star size={10} fill="currentColor" /> <span className="text-[#777]">4.5/5</span></div><p className="mt-1 text-xs font-bold">{item[1]}</p></article> }

export default function HomePage() { return <StorefrontFrame current="Homepage">
  <section className="relative -mx-0 overflow-hidden bg-[#f2f0ed] px-4 py-8 sm:-mx-12 sm:px-12 md:min-h-[300px] md:py-14"><div className="relative z-10 max-w-[430px]"><p className="mb-3 text-[10px] font-semibold uppercase tracking-[2px]">New season / 2024</p><h1 className="text-balance text-[31px] font-black leading-[.9] tracking-[-1.5px] sm:text-[54px]">FIND CLOTHES THAT MATCHES YOUR STYLE</h1><p className="mt-4 max-w-[330px] text-xs leading-5 text-[#666]">Browse through our diverse range of meticulously crafted garments, designed to bring out your individuality.</p><a href="/category" className="mt-6 inline-flex items-center rounded-full bg-black px-8 py-3 text-xs font-semibold text-white">Shop Now <ArrowRight className="ml-2" size={14} /></a><div className="mt-6 grid grid-cols-2 gap-x-4 gap-y-3 text-center text-[9px] text-[#555] sm:flex sm:gap-5 sm:text-left"><span><b className="block text-lg text-black">200+</b>International Brands</span><span><b className="block text-lg text-black">2,000+</b>High-Quality Products</span><span className="col-span-2 sm:col-span-1"><b className="block text-lg text-black">30,000+</b>Happy Customers</span></div></div><img src={heroImage} alt="SHOP.CO style collection" className="relative mt-6 block h-[320px] w-full object-cover object-[58%_38%] sm:absolute sm:bottom-0 sm:right-[-18%] sm:mt-0 sm:h-full sm:w-[58%] sm:object-left md:block" /></section>
  <div className="flex items-center justify-around bg-black py-4 text-sm font-bold text-white"><span>VERSACE</span><span>ZARA</span><span>GUCCI</span><span>PRADA</span><span>Calvin Klein</span></div>
  <section className="py-10"><h2 className="text-center text-2xl font-black tracking-[-1px]">NEW ARRIVALS</h2><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{products.map(item => <ProductCard item={item} key={item[0]} />)}</div><a href="/category" className="mx-auto mt-7 block w-fit rounded-full border border-[#ddd] px-8 py-2 text-xs">View All</a></section>
  <section className="border-t border-[#eee] py-10"><h2 className="text-center text-2xl font-black tracking-[-1px]">TOP SELLING</h2><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{topSelling.map(item => <ProductCard item={item} key={item[0]} />)}</div><a href="/category" className="mx-auto mt-7 block w-fit rounded-full border border-[#ddd] px-8 py-2 text-xs">View All</a></section>
  <section className="rounded-2xl bg-[#f1f1f1] p-6 sm:p-10"><h2 className="text-center text-2xl font-black tracking-[-1px]">BROWSE BY DRESS STYLE</h2><div className="mt-7 grid gap-3 sm:grid-cols-2"><a href="/category" className="relative h-32 overflow-hidden rounded-lg bg-white p-5 font-bold">Casual<img src={catalogImage} alt="Casual style" className="absolute right-0 top-0 h-full w-2/3 object-cover object-[20%_30%]" /></a><a href="/category" className="relative h-32 overflow-hidden rounded-lg bg-white p-5 font-bold">Formal<img src={catalogImage} alt="Formal style" className="absolute right-0 top-0 h-full w-2/3 object-cover object-[45%_50%]" /></a><a href="/category" className="relative h-32 overflow-hidden rounded-lg bg-white p-5 font-bold">Party<img src={catalogImage} alt="Party style" className="absolute right-0 top-0 h-full w-2/3 object-cover object-[66%_54%]" /></a><a href="/category" className="relative h-32 overflow-hidden rounded-lg bg-white p-5 font-bold">Gym<img src={catalogImage} alt="Gym style" className="absolute right-0 top-0 h-full w-2/3 object-cover object-[85%_54%]" /></a></div></section>
  <section className="py-10"><div className="flex items-center justify-between"><h2 className="text-2xl font-black tracking-[-1px]">OUR HAPPY CUSTOMERS</h2><div className="flex gap-2"><ChevronLeft size={18} /><ChevronRight size={18} /></div></div><div className="mt-5 grid gap-3 md:grid-cols-3"><blockquote className="rounded-lg border border-[#ddd] p-5 text-xs leading-5"><div className="text-amber-500">★★★★★</div><b className="block mt-2">Sarah M.</b><p className="mt-2 text-[#666]">The quality and fit are incredible. I found pieces that feel made for me.</p></blockquote><blockquote className="rounded-lg border border-[#ddd] p-5 text-xs leading-5"><div className="text-amber-500">★★★★★</div><b className="block mt-2">Alex K.</b><p className="mt-2 text-[#666]">Fast delivery, beautiful details, and an easy shopping experience.</p></blockquote><blockquote className="rounded-lg border border-[#ddd] p-5 text-xs leading-5"><div className="text-amber-500">★★★★★</div><b className="block mt-2">James L.</b><p className="mt-2 text-[#666]">SHOP.CO is now my first stop for everyday essentials.</p></blockquote></div></section>
  </StorefrontFrame> }
