"use client"

import { useMemo, useState } from "react"
import { Check, ChevronDown, ChevronRight, SlidersHorizontal, X } from "lucide-react"
import { StorefrontFrame } from "@/components/storefront-header"
import { StorefrontProductCard } from "@/components/storefront-product-card"
import { brands, categoryTree, colors, mockProducts, sizes } from "@/lib/storefront/catalog"


function FilterPanel({ onClose, selectedColors, setSelectedColors, selectedBrands, setSelectedBrands, selectedCategories, setSelectedCategories, selectedStyles, setSelectedStyles }: { onClose?: () => void; selectedColors: string[]; setSelectedColors: (colors: string[]) => void; selectedBrands: string[]; setSelectedBrands: (brands: string[]) => void; selectedCategories: string[]; setSelectedCategories: (categories: string[]) => void; selectedStyles: string[]; setSelectedStyles: (styles: string[]) => void }) {
  const [selectedSize, setSelectedSize] = useState("Large")
  const [expandedCategories, setExpandedCategories] = useState<string[]>([])
  const toggleCategory = (category: string) => setSelectedCategories((current) => current.includes(category) ? current.filter((item) => item !== category) : [...current, category])
  const toggleExpanded = (category: string) => setExpandedCategories((current) => current.includes(category) ? current.filter((item) => item !== category) : [...current, category])
  const categoryButton = (item: string, nested = false) => { const selected = selectedCategories.includes(item); return <label key={item} className={`flex w-full cursor-pointer items-center gap-2 py-2 text-left text-xs ${nested ? "pl-5 text-muted-foreground" : "text-foreground"}`}><input type="checkbox" checked={selected} onChange={() => toggleCategory(item)} className="peer sr-only" /><span aria-hidden="true" className={`flex size-4 shrink-0 items-center justify-center rounded border ${selected ? "border-primary bg-primary text-primary-foreground" : "border-[#bbb] bg-background"}`}>{selected && <Check size={11} />}</span>{item}</label> }
  return <div className="flex flex-col gap-5 text-sm"><div className="sr-only">Product filters</div>
    <div><div className="mb-2 flex items-center justify-between font-bold">Categories <ChevronDown size={15} /></div>{categoryTree.map((category) => <div key={category.name}><div className="flex items-center"><div className="min-w-0 flex-1">{categoryButton(category.name)}</div>{category.children.length > 0 && <button type="button" onClick={() => toggleExpanded(category.name)} aria-label={`Show ${category.name} subcategories`} className="p-2 text-muted-foreground"><ChevronRight size={15} className={`transition-transform ${expandedCategories.includes(category.name) ? "rotate-90" : ""}`} /></button>}</div>{expandedCategories.includes(category.name) && <div>{category.children.map((child) => categoryButton(child, true))}</div>}</div>)}</div>
    <div className="border-t border-border pt-4"><div className="mb-3 flex items-center justify-between font-bold">Price <ChevronDown size={15} /></div><input aria-label="Price range" type="range" min="50" max="300" defaultValue="240" className="w-full accent-black" /><div className="flex justify-between text-xs text-muted-foreground"><span>$50</span><span>$300</span></div></div>
    <div className="border-t border-border pt-4"><div className="mb-3 flex items-center justify-between font-bold">Colors <ChevronDown size={15} /></div><div className="flex flex-wrap gap-3">{colors.map((color) => { const selected = selectedColors.includes(color); return <button key={color} type="button" aria-label={`Color ${color}`} aria-pressed={selected} onClick={() => setSelectedColors(selected ? selectedColors.filter((item) => item !== color) : [...selectedColors, color])} className={`flex size-7 items-center justify-center rounded-full border-2 ${selected ? "border-black ring-2 ring-black ring-offset-2" : "border-[#ddd]"}`} style={{ backgroundColor: color }}>{selected && <Check size={14} className={color === "#fff" || color === "#f3d313" ? "text-black" : "text-white"} />}</button> })}</div></div><div className="border-t border-border pt-4"><div className="mb-3 flex items-center justify-between font-bold">Brand <ChevronDown size={15} /></div><div className="flex flex-col gap-2">{brands.map((brand) => { const selected = selectedBrands.includes(brand); return <button key={brand} type="button" aria-pressed={selected} onClick={() => setSelectedBrands(selected ? selectedBrands.filter((item) => item !== brand) : [...selectedBrands, brand])} className={`flex items-center gap-2 text-left text-xs ${selected ? "font-bold text-foreground" : "text-muted-foreground"}`}><span aria-hidden="true" className={`flex size-4 items-center justify-center rounded border ${selected ? "border-primary bg-primary text-primary-foreground" : "border-[#bbb] bg-background"}`}>{selected && <Check size={11} />}</span>{brand}</button> })}</div></div>
    <div className="border-t border-border pt-4"><div className="mb-3 flex items-center justify-between font-bold">Size <ChevronDown size={15} /></div><div className="flex flex-wrap gap-2">{sizes.map((size) => <button key={size} onClick={() => setSelectedSize(size)} className={`rounded-full px-3 py-2 text-[11px] ${selectedSize === size ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{size}</button>)}</div></div>
    <div className="border-t border-border pt-4"><div className="mb-2 flex items-center justify-between font-bold">Dress Style <ChevronDown size={15} /></div>{["Casual", "Formal", "Party", "Gym"].map((item) => { const selected = selectedStyles.includes(item); return <label key={item} className={`flex w-full cursor-pointer items-center justify-between py-2 text-left text-xs ${selected ? "font-bold text-foreground" : "text-muted-foreground"}`}><span className="flex items-center gap-2"><input type="checkbox" checked={selected} onChange={() => setSelectedStyles(selected ? selectedStyles.filter((style) => style !== item) : [...selectedStyles, item])} className="size-4 accent-black" />{item}</span><ChevronRight size={14} /></label>})}</div>
    {onClose && <button onClick={onClose} className="mt-auto rounded-full bg-primary py-3 text-xs text-primary-foreground">Apply Filter</button>}
  </div>
}

export default function CategoryPage() {
  const [sort, setSort] = useState("Most Popular")
  const [filtersOpen, setFiltersOpen] = useState(false)
  const [selectedColors, setSelectedColors] = useState<string[]>([])
  const [selectedBrands, setSelectedBrands] = useState<string[]>([])
  const [selectedCategories, setSelectedCategories] = useState<string[]>([])
  const [selectedStyles, setSelectedStyles] = useState<string[]>([])
  const styleForProduct = (name: string) => name.includes("Polo") || name.includes("Vertical") || name.includes("Checkered") ? "Formal" : name.includes("Gym") ? "Gym" : name.includes("Party") ? "Party" : "Casual"
  const categoryForProduct = (name: string) => name.includes("Jeans") ? "Jeans" : name.includes("Shorts") ? "Shorts" : name.includes("Shirt") || name.includes("T-shirt") ? (name.includes("T-shirt") ? "T-shirts" : "Shirts") : "Hoodies"
  const filteredProducts = useMemo(() => mockProducts.filter((product) => (selectedColors.length === 0 || selectedColors.includes(product.color)) && (selectedBrands.length === 0 || selectedBrands.includes(product.brand)) && (selectedCategories.length === 0 || selectedCategories.some((category) => category === categoryForProduct(product.name) || (category === "Graphic T-shirts" && product.name.includes("Graphic")) || (category === "Bermuda Shorts" && product.name.includes("Bermuda")))) && (selectedStyles.length === 0 || selectedStyles.includes(styleForProduct(product.name)))), [selectedColors, selectedBrands, selectedCategories, selectedStyles])
  const sortedProducts = useMemo(() => sort === "Price: Low to High" ? [...filteredProducts].sort((a, b) => a.price - b.price) : filteredProducts, [sort, filteredProducts])
  return <StorefrontFrame>
    <div className="w-full">
      <nav className="flex items-center gap-2 py-5 text-xs text-muted-foreground" aria-label="Breadcrumb"><a href="/" className="hover:underline">Home</a><span>›</span><span className="text-foreground">Shop</span></nav>
      <div className="mb-6 flex items-center justify-between gap-4"><div><h1 className="text-3xl font-black tracking-tight">All Styles</h1><p className="mt-2 text-sm text-muted-foreground">Explore our complete collection of styles made for every occasion.</p></div><div className="flex items-center gap-4 text-xs text-muted-foreground"><span className="hidden sm:inline">Showing {sortedProducts.length} of {mockProducts.length} Products</span><label className="flex items-center gap-1 text-foreground">Sort by <select value={sort} onChange={(event) => setSort(event.target.value)} className="bg-transparent font-bold outline-none"><option>Most Popular</option><option>Price: Low to High</option></select></label></div></div>
      <button type="button" onClick={() => setFiltersOpen(true)} className="mb-5 flex w-full items-center justify-center gap-2 rounded-full bg-primary py-3 text-sm font-semibold text-primary-foreground lg:hidden"><SlidersHorizontal size={16} /> Filters</button>
      <div className="grid items-start gap-8 lg:grid-cols-[210px_1fr]"><aside className="sticky top-6 hidden h-fit self-start rounded-xl border border-border p-5 lg:block"><div className="mb-5 flex items-center justify-between text-sm font-bold">Filters <SlidersHorizontal size={16} /></div><FilterPanel selectedColors={selectedColors} setSelectedColors={setSelectedColors} selectedBrands={selectedBrands} setSelectedBrands={setSelectedBrands} selectedCategories={selectedCategories} setSelectedCategories={setSelectedCategories} selectedStyles={selectedStyles} setSelectedStyles={setSelectedStyles} /></aside><section className="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-4 lg:gap-x-6">{sortedProducts.map((product) => <StorefrontProductCard key={product.name} product={product} />)}</section></div>
      {filtersOpen && <div className="fixed inset-0 z-50 bg-background text-foreground p-4 lg:hidden"><div className="mb-5 flex items-center justify-between border-b border-border pb-4"><h2 className="text-base font-bold">Filters</h2><button type="button" onClick={() => setFiltersOpen(false)} aria-label="Close filters"><X size={20} /></button></div><FilterPanel onClose={() => setFiltersOpen(false)} selectedColors={selectedColors} setSelectedColors={setSelectedColors} selectedBrands={selectedBrands} setSelectedBrands={setSelectedBrands} selectedCategories={selectedCategories} setSelectedCategories={setSelectedCategories} selectedStyles={selectedStyles} setSelectedStyles={setSelectedStyles} /></div>}
    </div>
  </StorefrontFrame>
}
